#!/usr/bin/env python3
"""Generate the vendored icon table for the CodeCeremony component library.

Reads a curated set of Lucide icons and writes a Go source file holding their
inner markup, normalised to the design contract: 24px grid, 1.75px stroke,
currentColor, round caps and joins.

Why a Go table rather than a template partial:

  - the markup is data, not presentation, so a Go map is the honest home for it;
  - rendering is a map lookup instead of a 74-branch if-chain in the template;
  - an unknown name is a compile-time-visible absence rather than a silently
    empty <svg>, which matters because the inventory is closed.

The design document approves Lucide (section 10.1) and requires icons to be
inlined as SVG with nothing fetched at runtime, so the path data is compiled
into the binary rather than served from a sprite sheet or a CDN.

Usage, from the repository root, with the npm tarball extracted at ./package:

    npm pack lucide-static@latest && tar xzf lucide-static-*.tgz
    python3 scripts/gen_icons.py
    rm -rf package lucide-static-*.tgz

Pass --check to verify the committed module matches the pinned Lucide release
without writing, which is what CI runs so a stale icon set is a failure rather
than a surprise.
"""

from __future__ import annotations

import pathlib
import re
import sys
import xml.etree.ElementTree as ET

# The names this portal uses. A name absent from this list cannot be rendered,
# which is the point: the inventory is closed, so an implementation cannot reach
# for a glyph that was never reviewed.
ICONS = {
    # shell and navigation
    "house", "layout-dashboard", "gauge", "users", "user", "settings",
    "shield", "folder-kanban", "list-checks", "file-text", "download",
    "bar-chart-3", "menu", "panel-left", "chevron-right", "chevron-down",
    "chevron-left", "log-out", "external-link", "search", "plus", "x",
    "ellipsis", "refresh-cw", "filter", "arrow-right", "arrow-up", "arrow-down",
    "log-in", "log-out", "tag", "tags",
    # status, per design.md section 10.3
    "circle-check", "circle-alert", "circle-slash", "alert-triangle", "info",
    "clock", "ban", "check", "minus", "lock", "unlock", "eye", "eye-off",
    # domain
    "calendar", "trophy", "scale", "gavel", "clipboard-list", "message-square",
    "thumbs-up", "award", "activity", "database", "key", "bell", "mail",
    "link", "image", "globe", "map-pin", "hash", "at-sign", "trash-2", "pencil",
    "git-branch", "star", "sparkles", "circle-help", "life-buoy", "book-open",
    "graduation-cap", "megaphone", "vote", "network", "route", "flag",
}

SOURCE = pathlib.Path("package/icons")
TARGET = pathlib.Path("web/src/lib/icons.generated.ts")
LUCIDE_VERSION = "1.48.0"

# design.md 10.1: Lucide is authored at 2px; the contract specifies 1.75px so
# the set matches the weight of ink body text rather than reading heavier.
STROKE_WIDTH = "1.75"

LICENSE = "ISC License, Copyright (c) 2026 Lucide Icons and Contributors"
SVG_NS = "{http://www.w3.org/2000/svg}"


def inner(name: str) -> str | None:
    """Return the children of one Lucide svg as normalised markup."""
    path = SOURCE / f"{name}.svg"
    if not path.exists():
        return None
    root = ET.fromstring(path.read_text())
    if root.tag != f"{SVG_NS}svg":
        return None

    parts: list[str] = []
    for child in root:
        tag = child.tag.replace(SVG_NS, "")
        attrs = " ".join(
            f'{key}="{value}"'
            for key, value in child.attrib.items()
            if key not in {"class", "width", "height", "stroke-width"}
        )
        # Re-quote path data, which Lucide emits with double quotes.
        attrs = attrs.replace("&quot;", '"')
        body = (child.text or "").strip()
        if not body:
            parts.append(f"<{tag} {attrs} />")
        else:
            parts.append(f'<{tag} {attrs}>{body}</{tag}>')
    return "".join(parts) if parts else None


def ts_string(value: str) -> str:
    """Quote for a TypeScript string literal."""
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def main() -> int:
    if not SOURCE.is_dir():
        print(
            f"error: {SOURCE} not found; extract the lucide-static tarball first",
            file=sys.stderr,
        )
        return 1

    found: dict[str, str] = {}
    missing: list[str] = []
    for name in sorted(ICONS):
        markup = inner(name)
        if markup:
            found[name] = markup
        else:
            missing.append(name)

    if missing:
        print(
            f"error: {len(missing)} icons not in lucide-static: {', '.join(missing)}",
            file=sys.stderr,
        )
        return 1

    # A map key must be a quoted string: Lucide names contain hyphens, which are
    # not valid in a bare Go identifier, so an unquoted key silently fails to
    # parse for exactly the names most likely to be used.
    width = len(max(found, key=len)) + 2
    lines = [
        "// Code generated by scripts/gen_icons.py from lucide-static "
        f"v{LUCIDE_VERSION}. DO NOT EDIT.",
        "//",
        "// Source: Lucide (ISC License, Copyright (c) 2026 Lucide Icons and",
        "// Contributors). Regenerate with:",
        "//   npm pack lucide-static@" + LUCIDE_VERSION + " && tar xzf lucide-static-*.tgz",
        "//   python3 scripts/gen_icons.py && rm -rf package lucide-static-*.tgz",
        "//",
        "// design.md 10.1 approves Lucide as the single icon family and requires",
        "// inline SVG with nothing fetched at runtime, because the one-command rule",
        "// has to work with the network off. Only the names listed in the generator",
        "// are present: the inventory is closed, so a glyph that was never reviewed",
        "// cannot be reached for by accident.",
        "//",
        "// The stroke width is 1.75, not Lucide's authored 2, per design.md 10.1, so",
        "// the set matches the weight of ink body text.",
        "",
        "/** The inner markup of each approved icon, on Lucide's 24px grid. The outer",
        " * <svg> is supplied by the Icon component so size and the accessibility",
        " * attributes are set in exactly one place. */",
        "export const ICON_MARKUP: Readonly<Record<string, string>> = {",
    ]
    for name, markup in found.items():
        lines.append(f"\t{ts_string(name).ljust(width)}: {ts_string(markup)},")
    lines += [
        "};",
        "",
        "/** Every approved icon name, sorted. The test suite asserts that each name a",
        " * component uses exists in ICON_MARKUP, which turns a missing glyph into a",
        " * test failure rather than an empty <svg> nobody notices. */",
        "export const ICON_NAMES: readonly string[] = Object.keys(ICON_MARKUP).sort();",
        "",
    ]

    rendered = "\n".join(lines) + "\n"
    if "--check" in sys.argv:
        if not TARGET.exists():
            print(f"error: {TARGET} does not exist; run scripts/gen_icons.py", file=sys.stderr)
            return 1
        if TARGET.read_text() != rendered:
            print(f"error: {TARGET} is out of date with lucide-static v{LUCIDE_VERSION}", file=sys.stderr)
            return 1
        print(f"{TARGET} is up to date ({len(found)} icons)")
        return 0

    TARGET.parent.mkdir(parents=True, exist_ok=True)
    TARGET.write_text(rendered)
    print(f"wrote {len(found)} icons to {TARGET}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
