#!/usr/bin/env python3
"""Generate the vendored icon table for the CodeCeremony component library.

Reads a curated set of Lucide icons and writes a Go source file holding their
inner markup, normalised to the design contract: 24px grid, 1.75px stroke,
currentColor, round caps and joins.

Why a Go table rather than a template partial:

  - the markup is data, not presentation, so a Go map is the honest home for it;
  - rendering is a map lookup instead of a 74-branch if-chain in the template;
  - an unknown name is a compile-time-visible absence rather than a silently
    empty <svg>, which matters because the inventory is closed.

The design document approves Lucide (section 10.1) and requires icons to be
inlined as SVG with nothing fetched at runtime, so the path data is compiled
into the binary rather than served from a sprite sheet or a CDN.

Usage, from the repository root, with the npm tarball extracted at ./package:

    npm pack lucide-static@latest && tar xzf lucide-static-*.tgz
    python3 scripts/gen_icons.py
    rm -rf package lucide-static-*.tgz
"""

from __future__ import annotations

import pathlib
import re
import sys
import xml.etree.ElementTree as ET

# The names this portal uses. A name absent from this list cannot be rendered,
# which is the point: the inventory is closed, so an implementation cannot reach
# for a glyph that was never reviewed.
ICONS = {
    # shell and navigation
    "house", "layout-dashboard", "gauge", "users", "user", "settings",
    "shield", "folder-kanban", "list-checks", "file-text", "download",
    "bar-chart-3", "menu", "panel-left", "chevron-right", "chevron-down",
    "chevron-left", "log-out", "external-link", "search", "plus", "x",
    "ellipsis", "refresh-cw", "filter", "arrow-right", "arrow-up", "arrow-down",
    # status, per design.md section 10.3
    "circle-check", "circle-alert", "circle-slash", "alert-triangle", "info",
    "clock", "ban", "check", "minus", "lock", "unlock", "eye", "eye-off",
    # domain
    "calendar", "trophy", "scale", "gavel", "clipboard-list", "message-square",
    "thumbs-up", "award", "activity", "database", "key", "bell", "mail",
    "link", "image", "globe", "map-pin", "hash", "at-sign", "trash-2", "pencil",
    "git-branch", "star", "sparkles", "circle-help", "life-buoy", "book-open",
    "graduation-cap", "megaphone", "vote", "network", "route", "flag",
}

SOURCE = pathlib.Path("package/icons")
TARGET = pathlib.Path("backend/internal/httpapi/icons.go")

# design.md 10.1: Lucide is authored at 2px; the contract specifies 1.75px so
# the set matches the weight of ink body text rather than reading heavier.
STROKE_WIDTH = "1.75"

LICENSE = "ISC License, Copyright (c) 2026 Lucide Icons and Contributors"
SVG_NS = "{http://www.w3.org/2000/svg}"


def inner(name: str) -> str | None:
    """Return the children of one Lucide svg as normalised markup."""
    path = SOURCE / f"{name}.svg"
    if not path.exists():
        return None
    root = ET.fromstring(path.read_text())
    if root.tag != f"{SVG_NS}svg":
        return None

    parts: list[str] = []
    for child in root:
        tag = child.tag.replace(SVG_NS, "")
        attrs = " ".join(
            f'{key}="{value}"'
            for key, value in child.attrib.items()
            if key not in {"class", "width", "height", "stroke-width"}
        )
        # Re-quote path data, which Lucide emits with double quotes.
        attrs = attrs.replace("&quot;", '"')
        body = (child.text or "").strip()
        if not body:
            parts.append(f"<{tag} {attrs} />")
        else:
            parts.append(f'<{tag} {attrs}>{body}</{tag}>')
    return "".join(parts) if parts else None


def go_string(value: str) -> str:
    """Quote for a Go interpreted string literal."""
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def main() -> int:
    if not SOURCE.is_dir():
        print(
            f"error: {SOURCE} not found; extract the lucide-static tarball first",
            file=sys.stderr,
        )
        return 1

    found: dict[str, str] = {}
    missing: list[str] = []
    for name in sorted(ICONS):
        markup = inner(name)
        if markup:
            found[name] = markup
        else:
            missing.append(name)

    if missing:
        print(
            f"error: {len(missing)} icons not in lucide-static: {', '.join(missing)}",
            file=sys.stderr,
        )
        return 1

    # A map key must be a quoted string: Lucide names contain hyphens, which are
    # not valid in a bare Go identifier, so an unquoted key silently fails to
    # parse for exactly the names most likely to be used.
    width = len(max(found, key=len)) + 2
    lines = [
        "// Code generated by scripts/gen_icons.py from lucide-static. DO NOT EDIT.",
        "",
        "// Source: Lucide (ISC License, Copyright (c) 2026 Lucide Icons and",
        f"// Contributors). Regenerate with: {LICENSE}",
        "",
        "// design.md section 10.1 approves Lucide as the single icon family and",
        "// requires inline SVG with nothing fetched at runtime, because the",
        "// one-command rule has to work with the network off. Only the icon names",
        "// listed in the generator are present: the inventory is closed, so a",
        "// glyph that was never reviewed cannot be reached for by accident.",
        "",
        "// The stroke width is 1.75 rather than Lucide's authored 2, per design.md",
        "// section 10.1, so the set matches the weight of ink body text.",
        "package httpapi",
        "",
        "// iconMarkup is the inner SVG for each approved Lucide icon, authored on",
        "// Lucide's 24px grid. The outer <svg> is supplied by the renderer so the",
        "// size and accessibility attributes are set in one place.",
        "var iconMarkup = map[string]string{",
    ]
    for name, markup in found.items():
        lines.append(f"\t{go_string(name).ljust(width)}: {go_string(markup)},")
    lines += [
        "}",
        "",
        "// iconNames is every approved icon, sorted. It exists so a template can",
        "// report the inventory rather than guess at it.",
        "var iconNames = []string{",
    ]
    for name in sorted(found):
        lines.append(f"\t{go_string(name)},")
    lines += [
        "}",
        "",
    ]

    TARGET.parent.mkdir(parents=True, exist_ok=True)
    TARGET.write_text("\n".join(lines))
    print(f"wrote {len(found)} icons to {TARGET}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
